### ISSUE TITLE
Real state prices : IVG-R

### ISSUE THREAD

**Issue by rafapereirabr** [wilsonfreitas/rbcb#1]
Wilson, congrats for the package. It's a fantastic initiative.

I was wondering if it would be possible to incorporate in the package BCB's data on real state prices , which are organized by BCB as the [IVG-R (Índice de Valores de Garantia de Imóveis Residenciais Financiados)](https://www.bcb.gov.br/glossario.asp?Definicao=1637&idioma=P&idpai=GLOSSARIO)

I've seen a few PDF reports on this index but I couldn't find IVG-R data on their website, though. I've already sent them an email requesting them to make this data publicly available on their open data portal.

best,

Rafael H M Pereira

**Comment by wilsonfreitas** [comment]
Hi @rafapereirabr,

This package relies on BCB open API, so that any information delivered by that API will be reacheable throught rbcb.
But I can figure out a few functions to extract information from others BCB reports.
I am planning a similar solution to extract information from FOCUS reports, which are PDF files.

Do you know where could I find the IVG-R report?

**Comment by JHMenegotto** [comment]
I think the package already gets the IVG-R data, no? The series number is 21340.
rbcb::get_series(21340)
If this is not the series, I apologize!

**Comment by rafapereirabr** [comment]
@JHMenegotto  Thanks, that's the series I was looking for ! Here is the [metadata](https://www3.bcb.gov.br/sgspub/localizarseries/localizarSeries.do?method=prepararTelaLocalizarSeries). 

Nonetheless, the series brings aggregate data for the whole country and I was trying to get these data disaggregated data by each metropolitan area.

ps. congratulations again for the package !

**Comment by samvignoli** [comment]
Almost all codes are here: https://docs.google.com/spreadsheets/d/1IViSl-xbjLFtvZSqPdhsxK9PtTxGnQthhYpRqcNgFvI/edit#gid=1046724696

**Comment by rafapereirabr** [comment]
This list is really usefull, @samvignoli . I think it should definitely be incorporated into the package documentation!


As I mentioned before, I was looking for the disaggregated IVG-R for each metropolitan area. I've contacted the BCB team but they told me they don't have this disaggregated information in their dystem and they don't have plans to make this information available. Here is their response:

>Senhor RAFAEL HENRIQUE MORAES PEREIRA,
> 
>Em atenção à sua manifestação registrada no canal da Ouvidoria, a área técnica responsável pelo >assunto presta os seguintes esclarecimentos:
> 
>"A série 21340, Índice de Valores de Garantia de Imóveis Residenciais Financiados (IVG-R), está >disponível no Sistema Gerenciador de Séries Temporais (SGS), acessível em >http://www4.bcb.gov.br/pec/series/port/aviso.asp.
>
>Com relação aos dados desagregados, informamos que o IVG-R é calculado a partir dos micro dados, >ou dados no nível mais individualizado, constantes do SCR (Sistema de Informações de Crédito) por >meio de software estatístico e sem a geração de dados intermediários. A disponibilização desses dados >demandaria significativo trabalho adicional de consolidação e avaliação que não poderia ser executado >sem prejuízo à rotina de atividades seja pela necessidade de reformulação do sistema, seja pela >escassez de recursos humanos. Pleitos semelhantes já foram negados, decisão esta respaldada pela >Comissão Mista de Reavaliação de Informações (CMRI), na Decisão no. 47, de 25/02/2015. Assim, o >Banco Central não incluirá tais dados em seu portal."
> 
> 
>Agradecemos o seu contato por entendermos que o uso deste canal de comunicação entre o cidadão e >o Banco Central é de suma importância, pois possibilita acesso direto a opiniões e sugestões, bem >como confere maior transparência às ações adotadas por esta Autarquia.
> 
>Atenciosamente,

**Comment by wilsonfreitas** [comment]
@samvignoli This list is amazing. I will figure out a way of using it in the package.
Thanks for contributing.
I planned using a web scraper to directly execute searches in SGS site, but SGS is tough. This list might be a first attempt on having a search which covers all series.
