### ISSUE TITLE
Install in ubuntu 18.04

### ISSUE THREAD

**Issue by gpetrini** [wilsonfreitas/rbcb#18]
Hello,
Recently I've updated my OS and I can't install rbcb anymore. Any other way to install it? I've tried using install.packages('rbcb') and by .tar
Tkx

**Comment by gpetrini** [comment]
I'm having problem with other packages that use Brazilian data like BETS, RIBGE and so on. My R version is 3.4.4

**Comment by wilsonfreitas** [comment]
Please, print the error message.
Let's try to find out what's going on.

**Comment by gpetrini** [comment]
`> install.packages("rbcb")
Installing package into ‘/home/gabriel/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘curl’, ‘openssl’, ‘httr’, ‘xml2’

tentando a URL 'https://cloud.r-project.org/src/contrib/curl_3.2.tar.gz'
Content type 'application/x-gzip' length 367047 bytes (358 KB)
==================================================
downloaded 358 KB

tentando a URL 'https://cloud.r-project.org/src/contrib/openssl_1.0.1.tar.gz'
Content type 'application/x-gzip' length 1194261 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

tentando a URL 'https://cloud.r-project.org/src/contrib/httr_1.3.1.tar.gz'
Content type 'application/x-gzip' length 147593 bytes (144 KB)
==================================================
downloaded 144 KB

tentando a URL 'https://cloud.r-project.org/src/contrib/xml2_1.2.0.tar.gz'
Content type 'application/x-gzip' length 251614 bytes (245 KB)
==================================================
downloaded 245 KB

tentando a URL 'https://cloud.r-project.org/src/contrib/rbcb_0.1.3.tar.gz'
Content type 'application/x-gzip' length 13641 bytes (13 KB)
==================================================
downloaded 13 KB

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘curl’
* removing ‘/home/gabriel/R/x86_64-pc-linux-gnu-library/3.4/curl’
* installing *source* package ‘openssl’ ...
** package ‘openssl’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because openssl was not found. Try installing:
 * deb: libssl-dev (Debian, Ubuntu, etc)
 * rpm: openssl-devel (Fedora, CentOS, RHEL)
 * csw: libssl_dev (Solaris)
 * brew: openssl@1.1 (Mac OSX)
If openssl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘openssl’
* removing ‘/home/gabriel/R/x86_64-pc-linux-gnu-library/3.4/openssl’
* installing *source* package ‘xml2’ ...
** package ‘xml2’ successfully unpacked and MD5 sums checked
Package libxml-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libxml-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libxml-2.0' found
Package libxml-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libxml-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libxml-2.0' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lxml2
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libxml-2.0 was not found. Try installing:
 * deb: libxml2-dev (Debian, Ubuntu, etc)
 * rpm: libxml2-devel (Fedora, CentOS, RHEL)
 * csw: libxml2_dev (Solaris)
If libxml-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘xml2’
* removing ‘/home/gabriel/R/x86_64-pc-linux-gnu-library/3.4/xml2’
ERROR: dependencies ‘curl’, ‘openssl’ are not available for package ‘httr’
* removing ‘/home/gabriel/R/x86_64-pc-linux-gnu-library/3.4/httr’
ERROR: dependencies ‘httr’, ‘xml2’ are not available for package ‘rbcb’
* removing ‘/home/gabriel/R/x86_64-pc-linux-gnu-library/3.4/rbcb’

The downloaded source packages are in
	‘/tmp/RtmpB8oHIW/downloaded_packages’
Warning messages:
1: In install.packages("rbcb") :
  installation of package ‘curl’ had non-zero exit status
2: In install.packages("rbcb") :
  installation of package ‘openssl’ had non-zero exit status
3: In install.packages("rbcb") :
  installation of package ‘xml2’ had non-zero exit status
4: In install.packages("rbcb") :
  installation of package ‘httr’ had non-zero exit status
5: In install.packages("rbcb") :
  installation of package ‘rbcb’ had non-zero exit status`

> library(rbcb)
Error in library(rbcb) : there is no package called ‘rbcb’

**Comment by lemuelemos** [comment]
You need install libxml2-dev on synapitic.

Em seg, 14 de mai de 2018 11:05, gpetrini <notifications@github.com>
escreveu:

**Comment by wilsonfreitas** [comment]
So @gpetrini, you have problems to install httr's dependencies: curl, openssl, xml2.
httr is necessary to download resources from the Internet, so if you can't install it you certainly will have problems to use any package that accesses online APIs.

The error message indicates that you don't have the native dependencies installed: libcurl, libxml-2.0 and maybe openssl.

Please, check out @lemuelemos suggestion.

Since this issue is not rbcb related I'm closing this. But, let me know if you get rbcb running properly.

**Comment by gpetrini** [comment]
Thanks for the suport. 
I've tried @lemuelemos method and still not working.

**Comment by gpetrini** [comment]
Yes, I tried that too

**Comment by gpetrini** [comment]
**Update**
Good news. I solved the problem. There were another packages not installed. I installed them by synapthic and worked fine! Thank you all for the suport.
