### ISSUE TITLE
Error when downloading market expectations

### ISSUE THREAD

**Issue by JHMenegotto** [wilsonfreitas/rbcb#28]
We have a problem with the server when downloading market expectations (the functions of the form get_xxx_market_expectations). It writes "Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer". I think it is the same issue as in 

https://stackoverflow.com/questions/51247912/jsonlite-suddenly-retunring-error-failure-when-receiving-data-from-the-peer/51520771#51520771

Maybe using readLines before the fromJSON function would fix it.

**Comment by thomazsarquis** [comment]
Same here! Any solutions?

**Comment by jccondi** [comment]
I was using the get_annual_market_expectations function (and similars) with no problems but suddenly it stopped working, presenting the same error above. I tried to reinstal the library but it didn't work. I didn't make any changes that could affect its usability. Any help???

**Comment by fabiocs8** [comment]
Same problem today with me

**Comment by wilsonfreitas** [comment]
Solved.
