### ISSUE TITLE
Problema com API

### ISSUE THREAD

**Issue by msperlin** [wilsonfreitas/rbcb#30]
Oi Wilson,

Seguinte, estou usando o rbcb mas desde ontem só retorna o seguinte erro:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL certificate problem: unable to get local issuer certificate

Imagino que o problema é no lado do BCB. Por acaso sabes como solucionar?

Segue meu código:

`
get.cdi.anual <- function(first.date = '2000-01-01', last.date = Sys.Date()) {
  require(rbcb)
  require(tidyverse)

  cat('\nFetching CDI Anual')

  my.code <- c(value = 4391)
  df.cdi <- get_series(my.code, start_date = first.date,
                       end_date = last.date) %>%
    mutate(series = 'CDI')

  return(df.cdi)
}
`

**Comment by msperlin** [comment]
Testei agora e voltou a funcionar. Tens ideia do que aconteceu? Lembro que no passado o API do SGS não era tão instável.

**Comment by wilsonfreitas** [comment]
Esse problema é muito instável e depende também do sistema operacional.
Por exemplo, nunca tive esse erro no Mac ou no Linux. No Windows costuma ser mais comum esse erro.
