### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by msperlin** [wilsonfreitas/rbcb#31]
Aproveitando, notei que o pacote foi retirado do CRAN. 

Foi decisão sua? Tens alguma perspectiva de retornar?

Sei que é chato aguentar as exigências do CRAN, mas o pacote fica mais fácil de acessar, principalmente para os alunos.

**Comment by msperlin** [comment]
Nao sei se lembras de mim, mas no conhecemos no SER/niteroi em 2017.

**Comment by wilsonfreitas** [comment]
Oi @msperlin.

O pacote foi removido do CRAN. O pacote começou a apresentar problemas de conexão com o site do BCB após a versão 3.5.
Em alguns sistemas operacionais o acesso retorna um erro que não consegui resolver e por isso o pacote foi removido do CRAN.

O erro ocorre ao usar a API JSON para acessar os dados do FOCUS.
A decisão era manter a funcionalidade e ficar fora do CRAN o removê-la e voltar ao CRAN.
Eu decidi mantê-la.

**Comment by msperlin** [comment]
Ja tive problema semelhante. O que eu fiz foi retirar qualquer acesso a internet no processo do CHECK. Assim ele não quebrava quando o site da B3 caia.
