### ISSUE TITLE
Erro ao buscar as séries

### ISSUE THREAD

**Issue by Smolski** [wilsonfreitas/rbcb#33]
Olá!

Estou com um erro quando busco as séries:

> rbcb::get_series(c(IPCA = 433, IGPM = 189), last = 12, as = "ts")
Error in .get_series(series_url(x, start_date, end_date, last)) : 
  BCB API Request error cannot open the connection

O que pode ser?

**Comment by andrecvalerio** [comment]
Estou tendo este mesmo erro ao tentar fazer download das séries também, mas parece se restringir apenas quando tento fazê-lo através do script. Se copio e colo o código diretamente no terminal, ele baixa as séries normalmente.

**Comment by wilsonfreitas** [comment]
Olá @Smolski e @andrecvalerio 

Muito estranho isso, essa API é bem estável, uso quase que diariamente.
Vocês estão dentro de algum firewall?

**Comment by wilsonfreitas** [comment]
Vou fechar essa issue, se tiverem mais evidências podemos reabri-la  novamente.
