### ISSUE TITLE
Is it possible to retrieve metadata as BETS package does?

### ISSUE THREAD

**Issue by GitHunter0** [wilsonfreitas/rbcb#38]
Hey @wilsonfreitas , is it possible to retrieve metadata as BETS package does via `BETS::BETSsearch()` ? 
It is an important feature and it would be great to have in rbcb.

As a side issue do you know why rbcb is so much faster than BETS? As discussed in here: https://github.com/nmecsys/BETS/issues/17

Thank you very much.

**Comment by wilsonfreitas** [comment]
Using the API, unfortunately no, it does not, but rbcb has a workaround. It scrapes the <https://dadosabertos.bcb.gov.br/> website and return the searches results with `rbcb::search_series`

Try

```r
rbcb::search_series("IPCA")
```

**Comment by GitHunter0** [comment]
Great to know @wilsonfreitas , is it possible to adjust the encoding type? Because the results with special characters get desfigured, e.g.: "Ãndice nacional de preÃ§os ao consumidor - Amplo (IPCA) - NÃºcleo por exclusÃ£o"

**Comment by GitHunter0** [comment]
> Great to know @wilsonfreitas , is it possible to adjust the encoding type? Because the results with special characters get desfigured, e.g.: "Ã�ndice nacional de preÃ§os ao consumidor - Amplo (IPCA) - NÃºcleo por exclusÃ£o"

@wilsonfreitas , I believe I know the solution. In your file "rbcb_search.R", replace `doc <- xml2::read_html(x)` with `doc <- xml2::read_html(x, enconding="UTF-16"))` . 

Please, would you mind to implement that to see if it works?

**Comment by wilsonfreitas** [comment]
I've made a small change using your suggestion and I believe that now it is working.

07fb9b10aab0b54b6c0a5477c67e7e3dfb4005d7 

Tks.
