### ISSUE TITLE
Error in get_currency

### ISSUE THREAD

**Issue by dutida21** [wilsonfreitas/rbcb#41]
This error appears when running the get_currency: "BCB API returned error: • Moeda não cadastrada."

Example:
brl_usd <- get_currency('USD', t_1y, t) %>%
  select(-bid) %>%
  rename(brl_usd = 2)

brl_eur <- get_currency('EUR', t_1y, t) %>%
  select(-bid) %>%
  rename(brl_eur= 2)

brl_gbp <- get_currency('GBP', t_1y, t) %>%
  select(-bid) %>%
  rename(brl_libra = 2)

**Comment by wilsonfreitas** [comment]
Is this still happening?
This API is very unstable.
