### ISSUE TITLE
Problem on get_annual_market_expectations

### ISSUE THREAD

**Issue by rachel-bastos-Mcp** [wilsonfreitas/rbcb#42]
Empty table is returned when trying to collect market expectations. It appears that the API is not returning data for some specific series.

In additional, the following warning is returned:

`Warning messages:
Unknown or uninitialised column: date. `

**Comment by wilsonfreitas** [comment]
Hi @rachel-bastos-Mcp 

The API has changed some indicators.
Here we have the current list of indicators.

```r
c("Balança comercial",
"Conta corrente",
"Investimento direto no país",
"Resultado primário",
"Resultado nominal",
"Dívida líquida do setor público",
"Dívida bruta do governo geral",
"IGP-M",
"IPCA",
"PIB Agropecuária",
"PIB Indústria",
"PIB Serviços",
"PIB Total",
"Preços administrados",
"Produção industrial",
"Selic",
"Câmbio")
```

The commit f6ba2cfc82959ead665a6292023678cdf888936f removes the indicators' check so you can pass any of these names to download the series.

**Comment by rachel-bastos-Mcp** [comment]
Thank you so much @wilsonfreitas!

**Comment by lucasauroque** [comment]
Before the changes, it was possible to get a long track record for the IPCA expected annually, using the "Meta para a taxa Selic-Over". Now, using only "Selic", it returns a short data series. Would anyone know how to get the full data?
