### ISSUE TITLE
Indic "Taxa de câmbio" is not avaliable

### ISSUE THREAD

**Issue by rmmaf** [wilsonfreitas/rbcb#43]
I have noticed that some indexes was changed on API, but when I try to get the monthly market expectations and use "Câmbio" (the newer version of "Taxa de câmbio")  as indic value and it returns the error below:
 
`Invalid indic argument: Câmbio`

Could you help me?

OBS: When I tried to use "Taxa de câmbio" as indic it returned this warning message:

`Warning messages:
1: Unknown or uninitialised column: date. 
2: Unknown or uninitialised column: reference_month. `

And the result dataframe is empty

**Comment by wilsonfreitas** [comment]
Hi @rmmaf see #42

**Comment by rmmaf** [comment]
I saw that issue, but didn't help me

**Comment by rmmaf** [comment]
I think you should have to update something

**Comment by wilsonfreitas** [comment]
I've update the other functions see 0c7b6e1528432b76e5162c228ee83d587b381270
I will figure out a way to discover the available indicators.
This API is a mess, you can't change the API without change its version.
