### ISSUE TITLE
Error when installing from devtools::install_github()

### ISSUE THREAD

**Issue by gabrielboechat** [wilsonfreitas/rbcb#48]
Hello everyone.

I can't install the package when using the command "devtools::install_github('wilsonfreitas/rbcb')". The message error is the following:

> Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\gboechat\Documents\R\R-4.0.5\library\00LOCK\rlang\libs\x64\rlang.dll to C:\Users\gboechat\Documents\R\R-4.0.5\library\rlang\libs\x64\rlang.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\gboechat\Documents\R\R-4.0.5\library\00LOCK\ellipsis\libs\x64\ellipsis.dll to C:\Users\gboechat\Documents\R\R-4.0.5\library\ellipsis\libs\x64\ellipsis.dll: Permission denied
3: In i.p(...) :
  installation of package ‘C:/Users/gboechat/AppData/Local/Temp/Rtmpg9dslQ/file48f83e48396a/rbcb_0.1.6.tar.gz’ had non-zero exit status

Am I missing any extra step prior to installing it?

Kind regards,

**Comment by wilsonfreitas** [comment]
This is weird, try to download the package (tar.gz), build it locally and install.

**Comment by gabrielboechat** [comment]
Thanks for the quick response, Wilson!

I installed the most recent R version (4.1.2) and it worked as usual.

Kind regards,
