### ISSUE TITLE
Problema ao puxar a Selic

### ISSUE THREAD

**Issue by henriquefpires** [wilsonfreitas/rbcb#49]
Boa tarde,

Faz alguns dias que um código (que sempre funcionou) parou de funcionar. A ideia é simples, só puxar a Selic:

end = '2022-02-01'
start = '2021-01-01'

selic_m <- rbcb::get_monthly_market_expectations("Selic", 
                                                start_date = start, 
                                                end_date = end) 

Agora retorna um DF vazio. Talvez tenha a ver com o fato do BC ter mudado a estrutura da variável selic de mensal (com buracos) para "reuniões"? Saberia me dizer o que pode estar ocorrendo?

Muito obrigado!

**Comment by wilsonfreitas** [comment]
Removendo o primeiro argumento ele retorna todos os dados do histórico.

Observando os indicadores retornados vemos que `Selic` não está na lista.

O BCB já fez isso no passado. Muito ruim né! Não tem muito o que fazer.

``` r
library(rbcb)

end = as.Date('2022-02-01')
start = as.Date('2021-01-01')

selic_m <- get_monthly_market_expectations(start_date = start,
                                           end_date = end)

selic_m$indic |> unique()
#>  [1] "IPCA"                          "Câmbio"                       
#>  [3] "IPCA Livres"                   "IPCA Serviços"                
#>  [5] "IPCA Bens industrializados"    "IPCA Alimentação no domicílio"
#>  [7] "IPCA Administrados"            "IGP-M"                        
#>  [9] "Taxa de desocupação"           "Produção industrial"          
#> [11] "INPC"                          "IPA-DI"                       
#> [13] "IPCA-15"                       "IPC-Fipe"                     
#> [15] "IGP-DI"                        "IPA-M"
```

<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by henriquefpires** [comment]
Horrível! Vamos aguardar. Valeu!
