### ISSUE TITLE
Mudança Expectativas de Mercado - Selic

### ISSUE THREAD

**Issue by lucasauroque** [wilsonfreitas/rbcb#50]
BCB alterou a forma de divulgação da Selic no sistema de expectativas de mercado. Dessa forma, a previsão mensal parou de ser divulgada. Em seu lugar, entrou expectativas por reunião. Sendo assim, a função que puxa expectativas mensais para a selic parou de funcionar.

Essa é a primeira vez que relato um problema via github. Se não fiz da forma mais adequada, peço desculpas antecipadamente.

Parabéns pelo pacote - ajuda demais!

**Comment by wilsonfreitas** [comment]
Oi @lucasauroque conversamos sobre isso aqui https://github.com/wilsonfreitas/rbcb/issues/49.

Na prática a `Selic` não é uma opção, é um argumento do filtro da API.
Com essa mudança esse filtro retorna 0 (zero) registros.
Se estiver retornando algo diferente disso é erro, caso contrário é o comportamento esperdo dada a mudança.

Se estiver aparecendo para você algo diferente disso pode enviar um código de exemplo, por favor?

**Comment by lucasauroque** [comment]
Oi @wilsonfreitas , obrigado pelo retorno. Ele retorna zero registros.
Meu ponto é que, pelo que estou entendendo, isso pode ser uma mudança permanente por parte do BCB. Na questão temporal, onde antes tínhamos apenas séries (i) mensais, (ii) trimestrais e (iii) anuais para a Selic, passaremos agora a ter uma periodicidade diferente, a saber, "por reunião", como uma consulta manual mostra, aqui: https://www3.bcb.gov.br/expectativas2/#/consultaSeriesEstatisticas

Dessa forma, *imagino* que o get_monthly_market_expectations não será mais uma fonte para Selic - não se tratando assim, de apenas bug temporário.

Abs!

**Comment by wilsonfreitas** [comment]
De fato!
O problema é que não há uma consulta informando os indicadores disponíveis e a [documentação](https://olinda.bcb.gov.br/olinda/servico/Expectativas/versao/v1/documentacao)  informa que a `Selic` é um indicador nessa API.

Entretanto, vi que há um novo endpoint específico para `Selic` e como você mencionou, a periodicidade é "por reunião".

Vou correr para implementar.

Obrigado.

**Comment by lucasauroque** [comment]
Eu que agradeço a atenção e disponibilidade, @wilsonfreitas . Bom trabalho!

**Comment by wilsonfreitas** [comment]
Foi implementado 5425267a5192c7442cd5871ee1725fd52ab9e4e3 a alteração para obter dados da Selic utilizando a nova API.
A caminho do CRAN versão 0.1.10
