### ISSUE TITLE
indic <- c("PIB Total", "Fiscal") 

### ISSUE THREAD

**Issue by danielsanchoR** [wilsonfreitas/rbcb#58]
Oi Wilson, espero encontrá-lo bem!

Por gentileza, extraí esse código da internet, mas não consigo chegar ao mesmo resultado. A priori, ('Meta para taxa over-selic', 'Fiscal') parecem não existir e não retornam informações. A última linha de código também não roda e chega a impedir a criação da base "data". 

data <- get_annual_market_expectations(c('PIB Total', 'IPCA', 'Câmbio',
                                         'Meta para taxa over-selic', 'Fiscal'),
                                       start_date = '2022-08-01') %>% 
  replace_na(replace = list(indic_detail = 'Média'))

**Comment by wilsonfreitas** [comment]
Opa @danielsanchoR 

Dá uma olhada aqui

https://olinda.bcb.gov.br/olinda/servico/Expectativas/versao/v1/documentacao#ExpectativasMercadoAnuais

Neste link tem os indicadores suportados atualmente pela API.
Houve uma mudança recente e os indicadores Meta para taxa over-selic e Fiscal não são mais suportados nessa API.

Atualmente os seguintes indicadores são suportados na API `get_annual_market_expectations`

> Balança Comercial / Câmbio / Conta corrente / Dívida bruta do governo geral / Dívida líquida do setor público / IGP-DI / IGP-M / INPC / Investimento direto no país / IPA-DI / IPA-M / IPCA / IPCA Administrados / IPCA Alimentação no domicílio / IPCA Bens industrializados / IPCA Livres / IPCA Serviços / IPCA-15 / IPC-FIPE / PIB Agropecuária / PIB Despesa de consumo da administração pública/ PIB despesa de consumo das famílias/ PIB Exportação de bens e serviços / PIB Formação Bruta de Capital Fixo / PIB Importação de bens e serviços / PIB Indústria / PIB Serviços / PIB Total/ Produção industrial / Resultado nominal / Resultado primário / Selic / Taxa de desocupação
