### ISSUE TITLE
Issue BCB API Request Error 500

### ISSUE THREAD

**Issue by ASLlohmann** [wilsonfreitas/rbcb#59]
Olà tudo bem. ?
Muito obrigado para seu package que facilita bastante a vida. 
Sempre usei sem problemas mas comeci a ter um mensagem regular de erro : 
 

`rbcb::get_market_expectations(type="monthly",    indic="IPCA")
`

```
Error in .get_series(url) : BCB API Request error 500
Content returned:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 suporte.ti@bcb.gov.br and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

Vocé tem alguma ideia da origem do problema ?

Obrigado

**Comment by wilsonfreitas** [comment]
Oi @ASLlohmann

As APIs do BCB são um pouco instáveis.
Se aguardar algumas horas ou tentar novamente no próximo dia deve funcionar.

Executei mesmo comando aqui e funcionou.
